# Generated by Django 3.1.3 on 2020-11-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Название')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('internal_id', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Внутренний ID')),
                ('avatar', models.TextField(blank=True, verbose_name='Аватар')),
                ('type_social', models.CharField(choices=[('VK', 'Vkontakte'), ('IN', 'Instagram'), ('TW', 'Twitter')], max_length=2, verbose_name='Социальная сеть')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_subscribers', models.IntegerField(default=0, verbose_name='Подписчики')),
                ('updated_at', models.DateTimeField(verbose_name='Обновлено')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.source')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
