# Generated by Django 3.1.3 on 2020-11-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20201125_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='source_id',
            new_name='source',
        ),
    ]
